version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Yxi8khU0wQjLc
    ports:
      - 127.0.0.1:27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Yxi8khU0wQjLc
      ME_CONFIG_MONGODB_URL: mongodb://root:Yxi8khU0wQjLc@mongo:27017/